# Advanced expressions in security
jms_security_extra:
  expressions: true
  voters:
    disable_acl: false
security:
  access_decision_manager:
    strategy: unanimous
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
  providers:
    in_memory:
      memory:
        users:
          %admin_login%: { password: %admin_password%, roles: ["ROLE_ADMIN"] }
  firewalls:
    main:
      pattern: ^/
      form_login:
        login_path:  /login
        check_path:  login_check
      logout:
        path:   /logout
        target: /
      anonymous: ~
  access_control:
    - { path: ^/(.+)/admin, role: ROLE_ADMIN }
