<?php

namespace Oneup\UploaderBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class YUI3Controller__JMSInjector
{
    public static function inject($container) {
        $instance = new \Oneup\UploaderBundle\Controller\YUI3Controller();
        return $instance;
    }
}
