<?php

namespace Oneup\UploaderBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AbstractChunkedController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Oneup\UploaderBundle\Controller\AbstractChunkedController();
        return $instance;
    }
}
