<?php

namespace SS\Bundle\AppBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/ekaterina/sites/diploma/app/cache/dev/jms_diextra/proxies/SS-Bundle-AppBundle-Controller-AdminController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('SS\\Bundle\\AppBundle\\Controller\\AdminController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'itemAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxya694449f_7ac88af0f2005aa610088f9d6381c07cd438caff\__CG__\SS\Bundle\AppBundle\Controller\AdminController();
        $instance->__CGInterception__setLoader($a);
        $refProperty = new \ReflectionProperty('SS\\Bundle\\AppBundle\\Controller\\AdminController', 'em');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('doctrine.orm.entity_manager', 1));
        return $instance;
    }
}
