<?php

namespace SS\Bundle\AppBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class IndexController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SS\Bundle\AppBundle\Controller\IndexController();
        $refProperty = new \ReflectionProperty('SS\\Bundle\\AppBundle\\Controller\\IndexController', 'repoPages');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('ss_app.repo.page', 1));
        $refProperty = new \ReflectionProperty('SS\\Bundle\\AppBundle\\Controller\\IndexController', 'repoImages');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('ss_app.repo.image', 1));
        return $instance;
    }
}
