<?php

namespace Werkint\Cms\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ArticleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Werkint\Cms\CoreBundle\Controller\ArticleController();
        $refProperty = new \ReflectionProperty('Werkint\\Cms\\CoreBundle\\Controller\\ArticleController', 'repoItem');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('werkint_cms_core.repo.item', 1));
        $refProperty = new \ReflectionProperty('Werkint\\Cms\\CoreBundle\\Controller\\ArticleController', 'em');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('doctrine.orm.entity_manager', 1));
        $refProperty = new \ReflectionProperty('Werkint\\Cms\\CoreBundle\\Controller\\ArticleController', 'engine');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('werkint_cms_core.twig.enviroment', 1));
        return $instance;
    }
}
