<?php

namespace Werkint\Bundle\FrameworkExtraBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HelperController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Werkint\Bundle\FrameworkExtraBundle\Controller\HelperController();
        $refProperty = new \ReflectionProperty('Werkint\\Bundle\\FrameworkExtraBundle\\Controller\\HelperController', 'config');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->getParameter('werkint_framework_extra'));
        return $instance;
    }
}
