<?php

namespace Werkint\Bundle\TemplatingBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TemplateController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Werkint\Bundle\TemplatingBundle\Controller\TemplateController();
        return $instance;
    }
}
